version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./keys:/etc/nginx/keys:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
  server:
    build: .
